language: ruby
rvm:
- 2.7.0
cache:
  bundler: true
  yarn: true
services:
- redis-server
- postgresql
before_install:
- sudo apt-get update
- sudo apt-get install google-chrome-stable
- nvm install --lts
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database go_movido_test;' -U postgres
env:
  secure: CfIFcl9IQfifoDDjZIFWniHhqo4hRBIjPO+0CCiA47NTX2MPcQiIM4s7fFnH0KcT1XJ15bm40jbRyaR2ian3i+IXITd8G78+21eWQzg8MiXMyERC09XkjSSeEZje1yrV4xBRCxeo9i7K8K5Gapq29K8U1F/BVNhBQknJouWTqAlfsed9GxYzvYaqbNoOTJZmmNROFPsd1BBSEzGZpIumbHvrqHH1DEz9axDpK09o2Qc16aWW03aOpfQp6Eoyyvay+/JDY3ojuBK7pFOmcjS0dN6lyeTYhU1esaR5T3l96hXjiKK6JheUl3TzoMfNpuFAhP+dxXzsGTTd7jk9GvJ8DJD9f2UgrSN8+Cdx7wq3l/w7nidCXPE4Jcajkqx9VnuuDYT3EiJnORokxElMaXCODN7WSnc0Osvx5TNVcuAbaoj83VWYoBELzHAlVh/cf4h80CISREGxz6BugQGFBTLmynikvFV/NoTkoCah2Ryf6WYyQ9cu/361kUoTP+BO+6w16+ofWozU4e/GwasgHZjGsYexfy8xGQijRIi47GQ4QAFEU85lIEzeNR+l4TE6h2BDII6BmasOdef2fhoXseNdzGNdbmbzC2niQmc5VAXBQakMUPX5uwp34jFZ8a2VmYejN8RjLa8yHGXwtt2GYF8M3GROcKgU6w7CLWygcHE2L6s=
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
- RAILS_ENV=production bundle exec rake assets:precompile
- bundle exec rspec
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ZljJ/mdpYEFD74I0R0NILmx08lB6ulY6gXG83qz991KPFmvi6dOkWFF3R5wzZK/fd4xrEeBJG7V7LfJOEwmYUuZoczUDldhU+AVmK6oD8zMxmCZYgj0RU70LtKhw6Qw0G1ixWTk5k01LL1sYoijU3MLtZsWPebMS8MLGvgyEk60UIBLlmwDgHGYJ1sYRMvgxwTyoSOnmPOReoAEG6LXP7PkdrdFH1mqQ/oAjtedAIy3hjCPKyCPOkgvHgtSZbc2f7yhcSENyu7L8XPuUiygSGhwPRO8oyyosxxcob3WmbB5mDzOFG5x6+l+bWimpwcRR6PKHFPOAntBMVK7jnF21806C9fih2fcSHbvm1Gf9auV49WmhxToS6L6+7bYSMm9/IeruePnd10gDBPabjGPrYV7X60E3/EtNqNXqIXJazureO3dYdjulRwuTtC9ICjSNBRYKFi9SG+fMHxjpv/fI8Zbcdm29N6ixah3CezqKCvyqk0Gs69AYyw0JWV8nEkDZKkfpFGPWI2n8mVFDlJ7EZov7Bcp9IRyg1Zv5cAskKNhUJoFKh6Cf0YVrN+Scb5pg2Ms1ol4KJ0HCc2O9H/SB9HtlHZGoCRGPjfMtNGkpCn/QNuYHgVp7poWm4wUQjbxwfIZbms48y4Do8lhySqtJaNhXwUPGEYikW+gOcW0IBTI=
  strategy: git
  app: movido-app-staging
  on:
    repo: yonitou/go-movido
  skip_cleanup: true
