language: ruby
rvm:
- 2.7.0
cache:
  bundler: true
  yarn: true
services:
- redis-server
- postgresql
before_install:
- sudo apt-get update
- sudo apt-get install google-chrome-stable
- nvm install --lts
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database go_movido_test;' -U postgres
env:
  secure: CfIFcl9IQfifoDDjZIFWniHhqo4hRBIjPO+0CCiA47NTX2MPcQiIM4s7fFnH0KcT1XJ15bm40jbRyaR2ian3i+IXITd8G78+21eWQzg8MiXMyERC09XkjSSeEZje1yrV4xBRCxeo9i7K8K5Gapq29K8U1F/BVNhBQknJouWTqAlfsed9GxYzvYaqbNoOTJZmmNROFPsd1BBSEzGZpIumbHvrqHH1DEz9axDpK09o2Qc16aWW03aOpfQp6Eoyyvay+/JDY3ojuBK7pFOmcjS0dN6lyeTYhU1esaR5T3l96hXjiKK6JheUl3TzoMfNpuFAhP+dxXzsGTTd7jk9GvJ8DJD9f2UgrSN8+Cdx7wq3l/w7nidCXPE4Jcajkqx9VnuuDYT3EiJnORokxElMaXCODN7WSnc0Osvx5TNVcuAbaoj83VWYoBELzHAlVh/cf4h80CISREGxz6BugQGFBTLmynikvFV/NoTkoCah2Ryf6WYyQ9cu/361kUoTP+BO+6w16+ofWozU4e/GwasgHZjGsYexfy8xGQijRIi47GQ4QAFEU85lIEzeNR+l4TE6h2BDII6BmasOdef2fhoXseNdzGNdbmbzC2niQmc5VAXBQakMUPX5uwp34jFZ8a2VmYejN8RjLa8yHGXwtt2GYF8M3GROcKgU6w7CLWygcHE2L6s=
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
- RAILS_ENV=staging bundle exec rake assets:precompile
- bundle exec rspec
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: CWj5CHDWCHsYTy+41WlipiF4FWUCwAgT7no96FmcpVfWHpipZVXMxkf/vmgktAVPJjX6AefO2BAgF3XtD1b6blJq732hOB3bk734J530yJAGNdEcPuR0aETuUL5wFe5WqZ7K5tIr0UCqiiToNkr6t2IdBen0bZGI+kihoNi0J3rpea/G5G9ei2iOAwecB8u2e6ux8fQTY8/pIPPT/COxj5vt+HDqmROicS9ji6bhlttRa9UjBXE+9acOcT1Rtqgs1cYosJSWo7eMPDOfCv2alWazPxsEGSpYN2XFGgqo6Ujm4Fm0OQDAajG1X4zojihRYrmvuUYRONQljxZgumNem0T5B0p0lqscYXDbKVrCQ4RGTqVUYPk+GacGJwTit4r9O1bSToirwqn2EZ8rX8ZyFl5VloXQ+YyCdMevF6VMNyoE8Db0pN4iOUcjB3y6YE4IRj2Ndmtu/PdoZb8MJVQzceu5a2tf4/zSZSkRtzX/acPmNBTDFFYRXx614lmJ2lqdsJ0HF/xi8HRUTmbl1aCZvIbc/1AC3BKkGQ/QkRoorcNRI/sd5UzubakjCmGEs6GTGaQy7yoRWXUOYcZ5OzJdnK27jMsZfYUTgprRP4JRcacQfU7Sj54p2zYCNewTUtjBh5ujrsOOrUTzyx/ASYfSgZqFuIBCeYou6c0fiuopg9k=
  app: movido-app-staging
  on:
    repo: yonitou/go-movido
  skip_cleanup: 'true'
