language: ruby
rvm:
- 2.7.2
cache:
  bundler: true
  yarn: true
services:
- redis-server
- postgresql
before_install:
- sudo apt-get update
- sudo apt-get install google-chrome-stable
- nvm install --lts
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database go_movido_test;' -U postgres
env:
  secure: CfIFcl9IQfifoDDjZIFWniHhqo4hRBIjPO+0CCiA47NTX2MPcQiIM4s7fFnH0KcT1XJ15bm40jbRyaR2ian3i+IXITd8G78+21eWQzg8MiXMyERC09XkjSSeEZje1yrV4xBRCxeo9i7K8K5Gapq29K8U1F/BVNhBQknJouWTqAlfsed9GxYzvYaqbNoOTJZmmNROFPsd1BBSEzGZpIumbHvrqHH1DEz9axDpK09o2Qc16aWW03aOpfQp6Eoyyvay+/JDY3ojuBK7pFOmcjS0dN6lyeTYhU1esaR5T3l96hXjiKK6JheUl3TzoMfNpuFAhP+dxXzsGTTd7jk9GvJ8DJD9f2UgrSN8+Cdx7wq3l/w7nidCXPE4Jcajkqx9VnuuDYT3EiJnORokxElMaXCODN7WSnc0Osvx5TNVcuAbaoj83VWYoBELzHAlVh/cf4h80CISREGxz6BugQGFBTLmynikvFV/NoTkoCah2Ryf6WYyQ9cu/361kUoTP+BO+6w16+ofWozU4e/GwasgHZjGsYexfy8xGQijRIi47GQ4QAFEU85lIEzeNR+l4TE6h2BDII6BmasOdef2fhoXseNdzGNdbmbzC2niQmc5VAXBQakMUPX5uwp34jFZ8a2VmYejN8RjLa8yHGXwtt2GYF8M3GROcKgU6w7CLWygcHE2L6s=
  global:
  - secure: aJkniI3isZ4el7AKbULROzqFfcXjMSe4pLG9FOWfJqGjAFYv0hTMjVHAviy3VPsnTssJ9iSc9NxhGgkx0aAjQPy/7GzVColDQfdBGwEjD6nO+OYBW1ZyE2SbgW2INiJinK22wAFP2+AXtPKaiTX3MVvkY2exJlRNOagTl6OE2b6qAZHubJ804+ZGNLi17elpS9R35MtPJ8vC2pWfC2SXViO6Y/nz3zsvAA+Patj3DzHm7J3dAcziKCsWANnI4ArLmiY/fN/HFMPCYPI+43T8H8CHDfl/U1OxqsHBTJJkDdA/k/Oa0VbCDMViMY88tVa6IR1qBd1/Gj/5bpESlgEpDd1SzVem9pi3I4n9jDUGHHj81WBYbX2Yz5K6/AJV7N3T6271WSZtQSct5BWb0ivFj7L+wS37T9JM62yze81QZb2VZRGGRnbntd/Xtgt8G1A2+G3GHJqNUfQyNYWD5vq5YCROW9QHnUs9lSxbo0w6/FQOIR2iuKEa/iGXG2ZeUHC/lc9fNcpjXMa5j1rOWKl5c2YmJm5WMdwgOFeuscgx6gzYLebPbx1oVzTOZrURHLDWfTgsLHvxVG/SuEtZKft4TD7TW3nHiqXkM1Ot0pD2VSH7qi5fbjayGWkuy8Enc96W4fCXXQ1phiTtj7Wl4U6WkA8p0R3Ez9YzLHod0MWr8KI=
  - secure: OPxOWo/CPe+ANGOedIvBePjUWh918qiZ768UPvEO+syarRU5OvbYFRkrC/ATIgWe0WyJRcarIpXoRpx1Q6H4yQMhOL0PFSYDQKnqwMKrMnC0k3XVuK0r6KRCBjfWLz/16p/w0HfyU8J3JvuKVm7clywmhxXjRJD5urC1V2PCd7LbMfC8fg2GHbkxzGLBe/fXX/B3VTbeOk1PNqImJupf7QgEHtSDu9mVE39Opl1RAXCc/uuljTzggqCdQNulXQIxXojBBoAcM2a6xQmtsV708aeJVJmmEWhLT9TFWCo9J45O7s6PrnLc8AYUmlsvXg+ikGZGl1rCvbBPVVrqVL9izz4Kcu7vit9k7Nz9C/RMJ3lN5d52lYJ04X8HXIy7FZ2PPset6Xw5gf590pT4mgTkCDmJ15RB+/gN5bx/H+vrwJjR6Tlsh0EnB1MT6atasn0xOmpKh19Um5KlhSEUB6nVQEcsY9VKxgyVzigEePgGUt4MOvmarAmwSIOcnLICz9kilRtdapdcXFAVuNtbhsDXyG6SLd2C1XCktK6i3EJwYEAEGRcsPAqNFRoOL045PXK1JIV8iHDCRXYlW02IWyy0kPNxBwvuq70+iD6r3iUV+WUteMYaAGuVh+BPiSJfIZyNaVxvKTIbSY9mn3wlcCBTQ3aoLTZCfuPwJ0A+LDLe7uQ=
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
- DB_ADAPTER=nulldb RAILS_ENV=production bundle exec rake assets:precompile
- bundle exec rspec
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: iDCT9DutwTdPl5sJy7kvgUJPlPKpROrcxWzFNh5aEWmcatpH2oirxpdvckZu/3HYusx93O3yayeoqZQ01k2bfUt0geVTFe3g85lCKVAsH4RxJTGF4zWHOUlg8sdsj63qFCloRkworlXk0zCAspH0UVjYtXirVPTO2JFoIyNe3ffZDlg8/CmACSlDS0BV0FQ1BqEeEcpPvV3vvWAA2377zTv3F5arm1aejJ0q8plYJOhSFgksF+ruLF9g2dZvsy8TSkIw7OQ+LaaWoTsOtUGCjViW5F5QLYDbimTtyHzruzzHpx0b0giobgjcqEIREhXo1vo3k8DPcCb8sqpPxJEtbU/X6xDsS7cpQgoVlopG3o3RIVTCTU/CDl02sQNEeNml1CXxMgY7AtmtRWx2Z7eZKglz56odxzzm4XtMffRwuBcMCpD7wcE1Twt0LZc/AXDPpXihX8XuMpx6veABt1CO/FsnOUX0qmDXlrcfm4f/CD2lrzgJIV8dE5EwdqYR0pQQEGhzwOtLTFrNsEi2dNsM383NzU8EtQCK16/E6SJ/+m0ZkgGOYls4XbFzEH2a+2AtLfTQQbg4wS+Hd70PA//PhChVvem9j9d5xU4Y6mr2uUvUXKjEpWI+6pOmbkWfYGNNmCsQYqV7L7Yc9WnumdrGDN0oZlDlCDczJmuPKjlcj2Y=
  strategy: git
  app: movido-app-staging
  on:
    repo: yonitou/go-movido
  skip_cleanup: true
