meta_product_name: "movido"
meta_title: "movido | Your companion for everything you need to get settled in your new city!"
meta_description: "Get your SIM card, local transport, WiFi, utilities and more - all in 5 mins, online and without fees"
meta_image: "meta_image.png"
