meta_product_name: "movido"
meta_title: "movido | Get set up in your new home in only 10 minutes"
meta_description: "Simply select all subscriptions you need - from mobile to new bank account - and let us deal with your admin work. And the best part: movido is 100% free!"
meta_image: "meta_image.png"
