development:
  forest_env_secret: 04d5d55b4b2287c8fbaa75a099fb56b9edff2e6fc190b7da1f2f9655e022e93e
  forest_auth_secret: nqjYfmGU8h3tqUfGfOKCWg
  application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  application_url: <%= ENV["APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  application_url: <%= ENV["APPLICATION_URL"] %>
