development:
  forest_env_secret: 11420eb3f37e36f55a86cc5114c1f7941b937ea752843278166d2aa3be25996d
  forest_auth_secret: a-IAQCnGMv9_r06-z1fOcg
  forest_application_url: http://localhost:3000
  forest_client_id: eyJraWQiOiJ6d0VjbU5LVVpVTkdYUnlNRzZ2QUoyTTVfYzBoZGhfblBXS0hYWjhGUTFBIiwiYWxnIjoiUlMyNTYifQ.eyJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6Im5vbmUiLCJyZWRpcmVjdF91cmlzIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC9mb3Jlc3QvYXV0aGVudGljYXRpb24vY2FsbGJhY2siXSwiZW52aXJvbm1lbnRfaWQiOjY5NjU4LCJpc3MiOiJGT1JFU1RfQVVUSEVOVElDQVRJT05fU1lTVEVNIiwiaWF0IjoxNjE0Nzg2NTcxfQ.MR3cSzB7RpU9tFdQHQZnr8dnDfjGsZdml8y3hBJZbrZ6cIe0CZPVTkyuabgtAVTbCg3NFHZdSV2U5OthwCniB75ZEXTkTjkhwffGmav4G3Nk5IwCmet_bsZDJsUBCLOZe7khgyMbjlm_KdGHvLn1Ntj_r9lojkQwS-J6-XXitwR8MfOaBFkwsZ1eD5jFZBerNtnXRhAGjxA6qNHMMCKSp5Yf5X56hwMzBNey5fq5HODO8XVnXLwZ716uMln0i5C3SErccGxDB3b-RuBJdfBYnm2kVcBtIgYeZZCbX5bP3kR_W15-mHMHV5gAehbkLbkykYC0E3mLNNKkq9NfAPJIAA
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
  forest_client_id: <%= ENV["FOREST_CLIENT_ID"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
  forest_client_id: <%= ENV["FOREST_CLIENT_ID"] %>
