development:
  forest_env_secret: 4653f1aa12111e786bba5a81b9862d1f3a7f4cb2f8eed05d0eb199a17cd1ef7c
  forest_auth_secret: 8CphpGYStuYcot2CKs_gmw
  forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
