mobile_phone_category = Category.create(name: 'mobile_phone')
transportation_category = Category.create(name: 'transportation')
pickup_category = Category.create(name: 'pickup')
Service.create(name: 'mobile_phone', category: mobile_phone_category)
Service.create(name: 'transportation', category: transportation_category)
Service.create(name: 'pickup', category: pickup_category)
fr = Country.create(code: 'fr')
gb = Country.create(code: 'gb')
bouygues = Company.create(name: 'Bouygues', logo_url: 'https://res.cloudinary.com/go-movido-com/image/upload/v1615298088/Company%20logos/bouygues_telecom_wcouac.png')
giffgaff = Company.create(name: 'GiffGaff', logo_url: 'https://res.cloudinary.com/go-movido-com/image/upload/v1615298087/Company%20logos/giffgaff_wwc1ca.png')
ratp = Company.create(name: 'RATP', logo_url: 'https://res.cloudinary.com/go-movido-com/image/upload/v1615298087/Company%20logos/ratp_itxvif.png')
oyster = Company.create(name: 'Oyster', logo_url: 'https://res.cloudinary.com/go-movido-com/image/upload/v1623066764/Company%20logos/357448_a3nv5r.svg')
uber = Company.create(name: 'Uber', logo_url: 'https://res.cloudinary.com/go-movido-com/image/upload/v1623066847/Company%20logos/kisspng-uber-real-time-ridesharing-logo-taxi-decal-motorista-5b3743a40c9164.4722731415303484520515_iqs0cf.jpg')
bouygues_product = Product.create(country: fr, company: bouygues, category: mobile_phone_category, description: "When arriving in France, you will instantly need a local phone number to make calls yourself and to receive incoming French calls.", name: 'Local SIM Card', activation_price: 39.90, subscription_price: 0, image_url: 'https://res.cloudinary.com/dxoeedsno/image/upload/v1624026837/Group_2345.png')
ratp_product = Product.create(country: fr, company: ratp, description: "Use your transportation card (“Navigo Card”) right away on the RER (regional express), the metro or the bus, a trip in the city center costs you €1.90", category: transportation_category, name: 'Public Transportation Card', activation_price: 16.90, subscription_price: 0, image_url: 'https://res.cloudinary.com/dxoeedsno/image/upload/v1624026836/navigo_4x-8.png')
uber_fr = Product.create(country: fr, company: uber, category: pickup_category, description: "Your personal driver will pick you up upon arrival and drop you off at your new home - 100\% safe, reliable & stress-free", name: 'Personal airport Pick-up to central Paris', activation_price: 55, subscription_price: 0, image_url: 'https://res.cloudinary.com/dxoeedsno/image/upload/v1624026838/Group_2433.png')
giffgaff_product = Product.create(country: gb, company: giffgaff, description: 'Upon arrival in the UK, you will instantly need a local phone number - to make/receive calls, for your National Insurance Number, or even your taxi', category: mobile_phone_category, name: 'Local SIM Card', activation_price: 1, subscription_price: 0, image_url: 'https://res.cloudinary.com/dxoeedsno/image/upload/v1624026838/Group_2348.png')
oyster_product = Product.create(country: gb, company: oyster, category: transportation_category, description: 'Use your London transportation card (“Oyster Card”) right away on the tube or bus, a trip in the city center costs you £2.40 with the Oyster Card', name: 'Public Transportation Card', activation_price: 15, subscription_price: 0, image_url: 'https://res.cloudinary.com/dxoeedsno/image/upload/v1624026837/oyster_final_4x-8.png')
uber_gb = Product.create(country: gb, company: uber, category: pickup_category, name: 'Personal airport Pick-up to central London', description: "Your personal driver will pick you up upon arrival and drop you off at your new home - 100\% safe, reliable & stress-free", activation_price: 60, subscription_price: 0, image_url: 'https://res.cloudinary.com/dxoeedsno/image/upload/v1624026839/Group_2343.png')
ProductDetail.create(product: bouygues_product, content: 'Includes 20 GB of data in France & Europe')
ProductDetail.create(product: bouygues_product, content: 'Includes unlimited calls & text in France & Europe')
ProductDetail.create(product: bouygues_product, content: 'Valid for 30 days')
ProductDetail.create(product: bouygues_product, content: 'Activate your SIM card once you are in France')
ProductDetail.create(product: ratp_product, content: 'Get your Paris public transportation card')
ProductDetail.create(product: ratp_product, content: 'Card comes with €15 credit')
ProductDetail.create(product: ratp_product, content: 'Top up your card at any metro station or online')
ProductDetail.create(product: ratp_product, content: 'Can be used directly upon arrival')
ProductDetail.create(product: uber_fr, content: 'Get picked up by a designated driver')
ProductDetail.create(product: uber_fr, content: 'Pick-up directly at the airport terminal')
ProductDetail.create(product: uber_fr, content: 'Your flight will be monitored for delays')
ProductDetail.create(product: uber_fr, content: 'Benefit from reduced movido fares')
ProductDetail.create(product: giffgaff_product, content: 'Get your GiffGaff SIM card')
ProductDetail.create(product: giffgaff_product, content: '£5 bonus credit with your first top-up')
ProductDetail.create(product: giffgaff_product, content: 'No contract guarantees full flexibility')
ProductDetail.create(product: giffgaff_product, content: 'All-in-one SIM size to fit all phones')
ProductDetail.create(product: oyster_product, content: 'Get your London public transportation card')
ProductDetail.create(product: oyster_product, content: 'Card comes with £5 deposit and £10 credit')
ProductDetail.create(product: oyster_product, content: 'Top up your card at any tube station or online')
ProductDetail.create(product: oyster_product, content: 'Can be used directly upon arrival')
ProductDetail.create(product: uber_gb, content: 'Get picked up by a designated driver')
ProductDetail.create(product: uber_gb, content: 'Pick-up directly at the airport terminal')
ProductDetail.create(product: uber_gb, content: 'Your flight will be monitored for delays')
ProductDetail.create(product: uber_gb, content: 'Benefit from reduced movido fares')


