// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Users = sequelize.define('users', {
    email: {
      type: DataTypes.STRING,
      defaultValue: "",
      allowNull: false,
    },
    encryptedPassword: {
      type: DataTypes.STRING,
      defaultValue: "",
      allowNull: false,
    },
    resetPasswordToken: {
      type: DataTypes.STRING,
    },
    resetPasswordSentAt: {
      type: DataTypes.DATE,
    },
    rememberCreatedAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    phone: {
      type: DataTypes.STRING,
    },
    country: {
      type: DataTypes.STRING,
    },
    notHoused: {
      type: DataTypes.BOOLEAN,
    },
    slug: {
      type: DataTypes.STRING,
    },
    username: {
      type: DataTypes.STRING,
    },
    birthCity: {
      type: DataTypes.STRING,
    },
    birthdate: {
      type: DataTypes.DATE,
    },
    city: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'users',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Users.associate = (models) => {
    Users.hasMany(models.billings, {
      foreignKey: {
        name: 'userIdKey',
        field: 'user_id',
      },
      as: 'billings',
    });
    Users.hasMany(models.addresses, {
      foreignKey: {
        name: 'userIdKey',
        field: 'user_id',
      },
      as: 'addresses',
    });
  };

  return Users;
};
